### ISSUE TITLE
Documentation Setup

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns#29]
This is the epic card for getting our documentation up to snuff. Actionable sub cards are referenced in this description. We can break this down further if any part seems too large or seems like it could be worked on simultaneously.

### Operator Guide - for setting up a production instance of VinylDNS #39
  - [ ] Install Guide
  -  [ ] Configuration Guide https://github.com/vinyldns/vinyldns/issues/27
  - [ ]  ~Monitoring Guide~

### User Guide - for end users of VinylDNS #40
  - [x] Portal Guide
  - [x] API Guide (existing API documentation)
  - [x] Tooling (existing tooling page)
  - [x] FAQ

### Developer Guide - for developers working on VinylDNS #42
  - [ ] Local install guide

### System Design - overview of how VinylDNS is structured. Will be linked to from other guides. #41
  - [x] Architecture
  - [x] Components
  -  [x] Integration

### RFC Guide  - how to go about proposing new features/significant changes #43
  - [x]  What is an RFC
  - [x] VinylDNS RFC process
  - [x] Example RFC

### Roadmap: short term and long term plans for VinylDNS #45

**Comment by mwinsl001c** [comment]
Can the documentation include a description of what problem(s) VinylDNS is solving?  How is the current way of doing things so bad?

**Comment by britneywright** [comment]
Completed.
