### ISSUE TITLE
Core Infrastructure Best Practice Badge

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#552]
https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md

- [x] The project website MUST succinctly describe what the software does (what problem does it solve?)
https://www.vinyldns.io/

- [x] The project website MUST provide information on how to: obtain, provide feedback (as bug reports or enhancements), and contribute to the software
https://www.vinyldns.io/contributing.html

- [x] The information on how to contribute MUST explain the contribution process (e.g., are pull requests used?) (URL required for "met".)
https://www.vinyldns.io/contributing.html

- [x] The software produced by the project MUST be released as FLOSS
https://github.com/VinylDNS/vinyldns - released as APL 2.0

- [x] The project MUST post the license(s) of its results in a standard location in their source repository. (URL required for "met".) 
https://github.com/vinyldns/vinyldns/blob/master/LICENSE

- [x] The project MUST provide basic documentation for the software produced by the project. (N/A allowed.) (Justification required for "N/A".)
README - https://github.com/vinyldns/vinyldns

- [x] The project MUST provide reference documentation that describes the external interface (both input and output) of the software produced by the project
https://www.vinyldns.io/api/

- [x] The project sites (website, repository, and download URLs) MUST support HTTPS using TLS
https://www.vinyldns.io/api/, https://github.com/vinyldns/vinyldns all sites are on HTTPS

- [x] The project MUST have one or more mechanisms for discussion (mailing list + gitter)
https://www.vinyldns.io/getting-help.html - Mailing group, email, gitter

- [x] The project SHOULD provide documentation in English and be able to accept bug reports and comments about code in English
Documentation - https://www.vinyldns.io/
Submitting an issue - https://www.vinyldns.io/contributing.html#submitting-an-issue

- [x] The project MUST have a version-controlled source repository that is publicly readable and has a URL
Github - https://github.com/VinylDNS/vinyldns

- [x] The project's source repository MUST track what changes were made, who made the changes, and when the changes were made
Github - https://github.com/VinylDNS/vinyldns

- [x] To enable collaborative review, the project's source repository MUST include interim versions for review between releases; it MUST NOT include only final releases
Github - https://github.com/VinylDNS/vinyldns

- [x] The project results MUST have a unique version identifier for each release intended to be used by users
Github Releases - https://github.com/vinyldns/vinyldns/releases

- [x] It is SUGGESTED that the Semantic Versioning (SemVer) format be used for releases
Using SemVer - https://github.com/vinyldns/vinyldns/releases

- [x] It is SUGGESTED that projects identify each release within their version control system. For example, it is SUGGESTED that those using git identify each release using git tags
Github Releases - https://github.com/vinyldns/vinyldns/releases

- [x] The project MUST provide, in each release, release notes that are a human-readable summary of major changes in that release to help users determine if they should upgrade and what the upgrade impact will be. The release notes MUST NOT be the raw output of a version control log (e.g., the "git log" command results are not release notes)
Example release notes - https://github.com/vinyldns/vinyldns/releases/tag/v0.8.0

- [x] The release notes MUST identify every publicly known vulnerability with a CVE assignment or similar that is fixed in each new release, unless users typically cannot practically update the software themselves
Note: None found so far

- [x] The project MUST provide a process for users to submit bug reports (e.g., using an issue tracker or a mailing list)
Using Github Issues - https://github.com/vinyldns/vinyldns/issues

- [x] The project SHOULD use an issue tracker for tracking individual issues
Github Issues - https://github.com/vinyldns/vinyldns/issues

- [x] The project MUST acknowledge a majority of bug reports submitted in the last 2-12 months (inclusive); the response need not include a fix
All bugs - https://github.com/vinyldns/vinyldns/issues?q=is%3Aopen+is%3Aissue+label%3Abug

- [x] The project SHOULD respond to a majority (>50%) of enhancement requests in the last 2-12 months (inclusive)
Closed bugs 27 of 34 - https://github.com/vinyldns/vinyldns/issues?q=is%3Aissue+label%3Abug+is%3Aclosed

- [x] The project MUST publish the process for reporting vulnerabilities on the project site. (URL required for "met".) 
**TODO: Add a section in CONTRIBUTING on reporting vulnerabilities (I thought we had this!)**

- [x] If private vulnerability reports are supported, the project MUST include how to send the information in a way that is kept private. (N/A allowed.) (URL required for "met".)

- [x] The project's initial response time for any vulnerability report received in the last 6 months MUST be less than or equal to 14 days.
None reported

- [x] If the software produced by the project requires building for use, the project MUST provide a working build system that can automatically rebuild the software from source code
Use sbt - https://github.com/vinyldns/vinyldns/blob/master/build.sbt

- [x] It is SUGGESTED that common tools be used for building the software
Use sbt - https://github.com/vinyldns/vinyldns/blob/master/build.sbt

- [x] The project SHOULD be buildable using only FLOSS tools
sbt is open source

- [x] The project MUST use at least one automated test suite that is publicly released as FLOSS
pytest for functional tests is FLOSS
scalacheck + sbt for unit tests is FLOSS

- [x] A test suite SHOULD be invocable in a standard way for that language
Tests are invoked through sbt - https://github.com/vinyldns/vinyldns/blob/master/DEVELOPER_GUIDE.md#testing

- [x] It is SUGGESTED that the test suite cover most (or ideally all) the code branches, input fields, and functionality
Codecov at 96% - https://codecov.io/gh/vinyldns/vinyldns

- [x] It is SUGGESTED that the project implement continuous integration
Continuous Integration implemented in Travis - https://travis-ci.org/vinyldns/vinyldns

- [x] The project MUST have a general policy (formal or not) that as major new functionality is added to the software produced by the project, tests of that functionality should be added to an automated test suite
Policy is documented here - https://github.com/vinyldns/vinyldns/blob/master/CONTRIBUTING.md#testing

- [x] The project MUST have evidence that the test_policy for adding tests has been adhered to in the most recent major changes to the software produced by the project
Policy is monitored in Codecov to ensure that coverage does not dip - https://codecov.io/gh/vinyldns/vinyldns

- [x] It is SUGGESTED that this policy on adding tests (see test_policy) be documented in the instructions for change proposals
Policy is documented here - https://github.com/vinyldns/vinyldns/blob/master/CONTRIBUTING.md#testing

- [x] The project MUST enable one or more compiler warning flags, a "safe" language mode, or use a separate "linter" tool to look for code quality errors or common simple mistakes, if there is at least one FLOSS tool that can implement this criterion in the selected language
Several Compiler options are enabled - https://github.com/vinyldns/vinyldns/blob/master/project/CompilerOptions.scala

- [x] The project MUST address warnings
Compiler warnings are fatal, meaning the build will not pass with warnings present

- [x] The project MUST have at least one primary developer who knows how to design secure software
We run several security scans at Comcast on the software, including pen testing and static analysis

- [x] At least one of the project's primary developers MUST know of common kinds of errors that lead to vulnerabilities in this kind of software, as well as at least one method to counter or mitigate each of them
We have remediated several issues over time, including this project.  Those include CSRF, MITM, weak ciphers, and secure headers on by default

- [x] The software produced by the project MUST use, by default, only cryptographic protocols and algorithms that are publicly published and reviewed by experts
Cryptography uses 256-bit AES key with CBC/PKCS5Padding - https://github.com/vinyldns/vinyldns/blob/master/modules/core/src/main/scala/vinyldns/core/crypto/JavaCrypto.scala

Note: Cryptography is **pluggable**, so users can bring their own

- [x] All functionality in the software produced by the project that depends on cryptography MUST be implementable using FLOSS
Implemented using standard Java crypto https://github.com/vinyldns/vinyldns/blob/master/modules/core/src/main/scala/vinyldns/core/crypto/JavaCrypto.scala

- [x] The security mechanisms within the software produced by the project MUST use default keylengths that at least meet the NIST minimum requirements through the year 2030 (as stated in 2012). It MUST be possible to configure the software so that smaller keylengths are completely disabled
By default, uses AES-256.  User can bring their own cryptography, it is easy to upgrade

- [x] The default security mechanisms within the software produced by the project MUST NOT depend on broken cryptographic algorithms (e.g., MD4, MD5, single DES, RC4, Dual_EC_DRBG), or use cipher modes that are inappropriate to the context

- [x] The security mechanisms within the software produced by the project MUST generate all cryptographic keys and nonces using a cryptographically secure random number generator, and MUST NOT do so using generators that are cryptographically insecure
Use org.apache.commons.lang3.RandomStringUtils for random string generation

- [x] If the software produced by the project causes the storing of passwords for authentication of external users, the passwords MUST be stored as iterated hashes with a per-user salt by using a key stretching (iterated) algorithm (e.g., PBKDF2, Bcrypt or Scrypt)
N/A - we do not store user passwords

- [x] The project MUST use a delivery mechanism that counters MITM attacks
Uses HTTPS as well as AWS SIG4 for request signing

- [x] A cryptographic hash (e.g., a sha1sum) MUST NOT be retrieved over http and used without checking for a cryptographic signature
Uses HTTPS as well as AWS SIG4 for request signing

- [x] There MUST be no unpatched vulnerabilities of medium or high severity that have been publicly known for more than 60 days
None have been found

- [x] The public repositories MUST NOT leak a valid private credential (e.g., a working password or private key) that is intended to limit public access
No private credentials are available.  Some test users and passwords are available but only used for functional testing

- [x] At least one static code analysis tool (beyond compiler warnings and "safe" language modes) MUST be applied to any proposed major production release of the software before its release, if there is at least one FLOSS tool that implements this criterion in the selected language
Use WartRemovers - https://github.com/vinyldns/vinyldns/blob/master/build.sbt#L57
https://github.com/wartremover/wartremover

- [x] All medium and high severity exploitable vulnerabilities discovered with static code analysis MUST be fixed in a timely way after they are confirmed
None have been discovered so far

**Comment by britneywright** [comment]
> If private vulnerability reports are supported, the project MUST include how to send the information in a way that is kept private. (N/A allowed.) (URL required for "met".)

https://github.com/vinyldns/vinyldns#contact
